***Machine Learning (IE406)***\
 **Asssignment 1**\
**Lukhi Krunalkumar - 201901449**

In [ ]:
import numpy.matlib
import math
import numpy as np

***Question 1***

In [ ]:
W=np.array([[8,5,1,5,6],
   [5,3,8,7,5],
   [1,8,10,7,8],
   [5,7,7,8,9],
   [6,5,8,9,7]])

*1.   Is the matrix W symmetric?*

In [ ]:
W_tran=W.transpose()
compare=W==W_tran
print(compare.all())

True


*2.   What is the maximum eigenvalue of W?*

In [ ]:
eval, evect=np.linalg.eig(W)
print(np.max(eval))

32.275416286869884


*3. What is the square root of maximum eigenvalue of W2?*

In [ ]:
W_sqr=np.dot(W,W)
eval_sqr,evect_sqr=np.linalg.eig(W_sqr)
print(math.sqrt(np.max(eval_sqr)))

32.275416286869856


*4. What is the Frobenius norm of the matrix?*

In [ ]:
print(np.linalg.norm(W))

33.52610922848042


*5. What is the determinant of the matrix? What is its rank?*

In [ ]:
print("determinant: "+str(np.linalg.det(W)))
print("rank: "+str(np.linalg.matrix_rank(W)))

determinant: 564.9999999999997
rank: 5


*6. Perform eigendecomposition of the symmetric matrix and print the eigenvector matrix Q, and the
diagonal matrix Λ with eigenvalues. Verify that matrix W equals $QΛQ^T$*

In [ ]:
print("Eigenvector Matrix Q:\n")
print(str(evect)+"\n")
print("Diagonal Matrix A with eigen value:\n")
print(str(np.diag(eval))+"\n")

product=np.dot(np.dot(evect,np.diag(eval)),evect.transpose())
print("Are QAQT and W Equal: "+str(np.allclose(product,W,1,1e5))+"\n")

Eigenvector Matrix Q:

[[-0.32686672 -0.78644991 -0.30823314 -0.41153047  0.10143812]
 [-0.39467476  0.04740538  0.68031453 -0.40169827 -0.46668534]
 [-0.49139203  0.60944275 -0.42781773 -0.40420933  0.20174294]
 [-0.50485227 -0.05022796 -0.3091631   0.59515818 -0.54111575]
 [-0.49096643 -0.07284208  0.40441889  0.38946466  0.66212433]]

Diagonal Matrix A with eigen value:

[[32.27541629  0.          0.          0.          0.        ]
 [ 0.          7.79874449  0.          0.          0.        ]
 [ 0.          0.         -4.50499151  0.          0.        ]
 [ 0.          0.          0.          0.95343025  0.        ]
 [ 0.          0.          0.          0.         -0.52259951]]

Are QAQT and W Equal: True



***Question 2***

In [ ]:
y0=np.array([0,1,0,0,0])
y0=y0.transpose()
b=np.array([1,0,0,0,0])
b=b.transpose()
y1=np.dot(y0,W)+b

*1. What is the value of $||y_1||_2$*

In [ ]:
print(np.linalg.norm(y1,2))

13.527749258468683


*2. What is the value of $||y_1||_2/||y_0||_2$*

In [ ]:
print(np.linalg.norm(y1,2)/np.linalg.norm(y0,2))

13.527749258468683


***Question 3: Orthogonal Matrix***

In [ ]:
A=(1/3)*np.array([[2,-2,1],[1,2,2],[2,1,-2]])
v=np.array([1,0,1])
v=v.transpose()

*1. What is the norm of vectors v and Av?*

In [ ]:
AV=np.dot(A,v)
print("norm of v: "+str(np.linalg.norm(v)))
print("norm of Av: "+str(np.linalg.norm(AV)))

norm of v: 1.4142135623730951
norm of Av: 1.4142135623730951


*2. Is the matrix A orthogonal?*

In [ ]:
AT=A.transpose()
AT=np.round(AT,5)
A_inv=np.linalg.inv(A)
print(np.allclose(AT,A_inv,1,1e5))

True
